In [90]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np 

In [106]:
X, _ = load_iris(return_X_y=True, as_frame=True)

Normalisation 


Covariance


Eigenvalues, eigenvectors via SVD et via AX = lambdaX 


Produit scalaire eigenvectors At

In [4]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [108]:
X[X.columns[0]] = X[X.columns[0]].apply(lambda x: x*100)

In [117]:
pca = PCA()
df = pd.DataFrame(pca.fit_transform(X))

In [110]:
df

0         1         2         3
0    -74.369993 -1.140853 -0.042611  0.004916
1    -94.365659 -0.600155  0.306296 -0.091286
2   -114.363617 -0.364597  0.037915 -0.026743
3   -124.357826  0.031398  0.049548  0.067244
4    -84.368043 -0.979937 -0.183699  0.061494
..          ...       ...       ...       ...
145   85.684548  0.052527 -0.162255 -0.448393
146   45.686178  0.646265  0.276404 -0.260037
147   65.686314  0.317808 -0.141100 -0.148720
148   35.698078  1.060918 -0.805128 -0.098185
149    5.695023  1.305240 -0.350889  0.126908

[150 rows x 4 columns]

In [56]:
pca.components_

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199],
       [-0.71956635,  0.24438178,  0.14212637,  0.63427274],
       [-0.26128628,  0.12350962,  0.80144925, -0.52359713]])

In [19]:
pca.explained_variance_ratio_

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [112]:
df['species'] = _

In [102]:
df

0         1         2         3  species
0   -2.684126  0.319397 -0.027915 -0.002262        0
1   -2.714142 -0.177001 -0.210464 -0.099027        0
2   -2.888991 -0.144949  0.017900 -0.019968        0
3   -2.745343 -0.318299  0.031559  0.075576        0
4   -2.728717  0.326755  0.090079  0.061259        0
..        ...       ...       ...       ...      ...
145  1.944110  0.187532  0.177825 -0.426196        2
146  1.527167 -0.375317 -0.121898 -0.254367        2
147  1.764346  0.078859  0.130482 -0.137001        2
148  1.900942  0.116628  0.723252 -0.044595        2
149  1.390189 -0.282661  0.362910  0.155039        2

[150 rows x 5 columns]

In [113]:
px.scatter(data_frame=df, x=0, y=1, color='species')

In [22]:
px.scatter(data_frame=df, x='PC1', y='PC2', color='species')

In [100]:
px.scatter_3d(data_frame=df, x=0, y=1, z=2, color='species')

In [58]:
temp = pd.DataFrame(X)
temp['species'] = _

In [101]:
px.scatter_3d(data_frame=temp, x=0, y=1, z=2, color='species')

In [25]:
np.cov(X.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [26]:
pca.get_covariance()

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [55]:
X.T.dot(X)

array([[150.        , -17.63546762, 130.76306638, 122.69116894],
       [-17.63546762, 150.        , -64.26601565, -54.91888988],
       [130.76306638, -64.26601565, 150.        , 144.42981471],
       [122.69116894, -54.91888988, 144.42981471, 150.        ]])

In [54]:
np.linalg.eig(X.T.dot(X))

EigResult(eigenvalues=array([437.77467248, 137.10457072,  22.01353134,   3.10722546]), eigenvectors=array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]]))

In [27]:
eigenvalues, eigenvectors = np.linalg.eig(pca.get_covariance())

In [45]:
eigenvalues

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [28]:
eigenvalues

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [29]:
eigenvectors

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

In [43]:
pd.DataFrame(X.dot(eigenvectors))

0         1         2         3
0   -2.264703 -0.480027 -0.127706  0.024168
1   -2.080961  0.674134 -0.234609  0.103007
2   -2.364229  0.341908  0.044201  0.028377
3   -2.299384  0.597395  0.091290 -0.065956
4   -2.389842 -0.646835  0.015738 -0.035923
..        ...       ...       ...       ...
145  1.870503 -0.386966  0.256274  0.389257
146  1.564580  0.896687 -0.026371  0.220192
147  1.521170 -0.269069  0.180178  0.119171
148  1.372788 -1.011254  0.933395  0.026129
149  0.960656  0.024332  0.528249 -0.163078

[150 rows x 4 columns]

In [41]:
pd.DataFrame(eigenvectors.T.dot(X.T)).T

0         1         2         3
0   -2.264703 -0.480027 -0.127706  0.024168
1   -2.080961  0.674134 -0.234609  0.103007
2   -2.364229  0.341908  0.044201  0.028377
3   -2.299384  0.597395  0.091290 -0.065956
4   -2.389842 -0.646835  0.015738 -0.035923
..        ...       ...       ...       ...
145  1.870503 -0.386966  0.256274  0.389257
146  1.564580  0.896687 -0.026371  0.220192
147  1.521170 -0.269069  0.180178  0.119171
148  1.372788 -1.011254  0.933395  0.026129
149  0.960656  0.024332  0.528249 -0.163078

[150 rows x 4 columns]

In [44]:
pca.singular_values_

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [51]:
eigenvalues, eigenvectors = np.linalg.eig(X.T.dot(X))

In [53]:
np.sqrt(eigenvalues)

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [49]:
X.T.dot(X)

array([[150.        , -17.63546762, 130.76306638, 122.69116894],
       [-17.63546762, 150.        , -64.26601565, -54.91888988],
       [130.76306638, -64.26601565, 150.        , 144.42981471],
       [122.69116894, -54.91888988, 144.42981471, 150.        ]])

In [50]:
pca.get_covariance()

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [64]:
df

PC1       PC2       PC3       PC4  species
0   -2.264703  0.480027 -0.127706 -0.024168        0
1   -2.080961 -0.674134 -0.234609 -0.103007        0
2   -2.364229 -0.341908  0.044201 -0.028377        0
3   -2.299384 -0.597395  0.091290  0.065956        0
4   -2.389842  0.646835  0.015738  0.035923        0
..        ...       ...       ...       ...      ...
145  1.870503  0.386966  0.256274 -0.389257        2
146  1.564580 -0.896687 -0.026371 -0.220192        2
147  1.521170  0.269069  0.180178 -0.119171        2
148  1.372788  1.011254  0.933395 -0.026129        2
149  0.960656 -0.024332  0.528249  0.163078        2

[150 rows x 5 columns]

In [136]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

rfc = RandomForestClassifier(max_depth=15)
X = df[[0]]

X_train, X_test, y_train, y_test = train_test_split(X, _)

In [137]:
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=15)

In [138]:
rfc.score(X_train, y_train)

1.0

In [139]:
rfc.score(X_test, y_test)

0.8947368421052632

In [114]:
X, _ = load_iris(return_X_y=True, as_frame=True)

In [115]:
rfc = RandomForestClassifier(max_depth=15)

X_train, X_test, y_train, y_test = train_test_split(X, _)
rfc.fit(X_train, y_train)

rfc.score(X_train, y_train), rfc.score(X_test, y_test)

(1.0, 0.9473684210526315)

In [141]:
lr = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(df, _)

In [142]:
lr.fit(X_train, y_train)

LogisticRegression()

In [143]:
lr.score(X_train, y_train)

0.9821428571428571

In [144]:
lr.score(X_test, y_test)

1.0

In [146]:
X, _ = load_iris(return_X_y=True, as_frame=True)
lr = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(df, _)
lr.fit(X_train, y_train)
lr.score(X_train, y_train), lr.score(X_test, y_test)

(0.9910714285714286, 0.9473684210526315)