# House prices reduction 

Let's check out the power of PCA on tabular data. Download the dataset here 👉👉 <a href="https://full-stack-bigdata-datasets.s3.eu-west-3.amazonaws.com/Machine+Learning+non+Supervis%C3%A9/PCA/house_prices.csv" target="_blank">House Prices</a>

1. Import `numpy` and `pandas`

In [46]:
# import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

import plotly.express as px 
import plotly.graph_objects as go


2. Import dataset and remove column `Id`

In [47]:
data = pd.read_csv("https://full-stack-bigdata-datasets.s3.eu-west-3.amazonaws.com/Machine+Learning+non+Supervis%C3%A9/PCA/house_prices.csv")
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [48]:
data=data.drop(columns="Id")
data.head()


MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          60       RL         65.0     8450   Pave   NaN      Reg   
1          20       RL         80.0     9600   Pave   NaN      Reg   
2          60       RL         68.0    11250   Pave   NaN      IR1   
3          70       RL         60.0     9550   Pave   NaN      IR1   
4          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
0         Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
1         Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
2         Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
3         Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
4         Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  
2       0      9    2008        WD         Normal     223500  
3       0      2    2006        WD        Abnorml     140000  
4       0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

3. Remove NaN

In [49]:
data.shape

(1460, 80)

In [50]:
data = data.dropna(axis="columns")
data.shape

(1460, 61)

4. Split data into `X` and `y` where X contains all columns except `SalePrice`

In [51]:
target = "SalePrice"

X = data.drop(columns=target)
y = data[target]
X.head()

MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
0          60       RL     8450   Pave      Reg         Lvl    AllPub   
1          20       RL     9600   Pave      Reg         Lvl    AllPub   
2          60       RL    11250   Pave      IR1         Lvl    AllPub   
3          70       RL     9550   Pave      IR1         Lvl    AllPub   
4          60       RL    14260   Pave      IR1         Lvl    AllPub   

  LotConfig LandSlope Neighborhood  ... OpenPorchSF EnclosedPorch 3SsnPorch  \
0    Inside       Gtl      CollgCr  ...          61             0         0   
1       FR2       Gtl      Veenker  ...           0             0         0   
2    Inside       Gtl      CollgCr  ...          42             0         0   
3    Corner       Gtl      Crawfor  ...          35           272         0   
4       FR2       Gtl      NoRidge  ...          84             0         0   

  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold SaleType SaleCondition  
0           0         0        0       2    2008       WD        Normal  
1           0         0        0       5    2007       WD        Normal  
2           0         0        0       9    2008       WD        Normal  
3           0         0        0       2    2006       WD       Abnorml  
4           0         0        0      12    2008       WD        Normal  

[5 rows x 60 columns]

In [52]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

5. Using <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html" target="_blank">`select_dtypes`</a> from Pandas, filter out all categorical variables. 

In [53]:
X = X.select_dtypes(exclude=["object"])
X.head()

MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0          60     8450            7            5       2003          2003   
1          20     9600            6            8       1976          1976   
2          60    11250            7            5       2001          2002   
3          70     9550            7            5       1915          1970   
4          60    14260            8            5       2000          2000   

   BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  ...  GarageArea  \
0         706           0        150          856  ...         548   
1         978           0        284         1262  ...         460   
2         486           0        434          920  ...         608   
3         216           0        540          756  ...         642   
4         655           0        490         1145  ...         836   

   WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  \
0           0           61              0          0            0         0   
1         298            0              0          0            0         0   
2           0           42              0          0            0         0   
3           0           35            272          0            0         0   
4         192           84              0          0            0         0   

   MiscVal  MoSold  YrSold  
0        0       2    2008  
1        0       5    2007  
2        0       9    2008  
3        0       2    2006  
4        0      12    2008  

[5 rows x 33 columns]

6. Split `X`, `y` in a train set and test set.
> NB: specify `random_state=0` and `test_size=0.2`

In [54]:

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)
X_train.head()

MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
618          20    11694            9            5       2007          2007   
870          20     6600            5            5       1962          1962   
92           30    13360            5            7       1921          2006   
817          20    13265            8            5       2002          2002   
302          20    13704            7            5       2001          2002   

     BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  ...  GarageArea  \
618          48           0       1774         1822  ...         774   
870           0           0        894          894  ...         308   
92          713           0        163          876  ...         432   
817        1218           0        350         1568  ...         857   
302           0           0       1541         1541  ...         843   

     WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  \
618           0          108              0          0          260         0   
870           0            0              0          0            0         0   
92            0            0             44          0            0         0   
817         150           59              0          0            0         0   
302         468           81              0          0            0         0   

     MiscVal  MoSold  YrSold  
618        0       7    2007  
870        0       8    2009  
92         0       8    2009  
817        0       7    2008  
302        0       1    2006  

[5 rows x 33 columns]

7. Import and fit `RandomForestRegressor` on your train set. Check out your score on X_test
> NB: specify `random_state=0` and `min_samples_split=15`

In [55]:
my_random_forest = RandomForestRegressor(random_state=0, min_samples_split=15)
my_random_forest.fit(X_train, y_train)
my_random_forest.score(X_test, y_test)

0.8366009574575247

8. Verify overfitting

In [56]:
my_random_forest.score(X_train, y_train)

0.945322157767256

9. Use cross validation to check your model overall performance : display the average score and the standard deviation
> NB: you can use <a href="https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html?highlight=cross%20val%20score#sklearn.model_selection.cross_val_score" target="_blank" >`cross_val_score`</a> from sklearn

In [57]:
scores = cross_val_score(my_random_forest, X_train, y_train, cv=25)
scores

array([0.84408484, 0.92121978, 0.87159194, 0.81829412, 0.95281324,
       0.69528887, 0.88008512, 0.25312327, 0.82353659, 0.93022963,
       0.89541079, 0.89355802, 0.89833128, 0.84354082, 0.89330607,
       0.82659114, 0.82030364, 0.86116028, 0.91333381, 0.80960393,
       0.88973339, 0.87521317, 0.91229801, 0.81887341, 0.89465573])

In [58]:
scores.mean()

0.8414472358819682

In [59]:
scores.std()

0.13084777590580488

10. Normalize your train set and apply it on your test set 

In [60]:
std = StandardScaler()
X_std_train = std.fit_transform(X_train)
X_std_test = std.transform(X_test)
X_std_train

array([[-0.86836547,  0.10321202,  2.13150648, ..., -0.09258767,
         0.25639595, -0.61356151],
       [-0.86836547, -0.37288066, -0.79485211, ..., -0.09258767,
         0.62339407,  0.88411842],
       [-0.63114155,  0.25891881, -0.79485211, ..., -0.09258767,
         0.62339407,  0.88411842],
       ...,
       [ 0.79220197, -0.15511546, -0.06326246, ..., -0.09258767,
        -0.84459842,  1.63295838],
       [ 1.50387373, -0.69102346,  0.66832719, ..., -0.09258767,
         1.35739032, -1.36240148],
       [ 0.08053021,  0.57762239,  0.66832719, ..., -0.09258767,
        -0.11060217,  1.63295838]])

11. Apply PCA on your normalized train set.
> NB: specify `n_components=3`

Bien voir qu'on avait 33 colonnes

In [61]:
# PCA with 3 components
pca = PCA(n_components=3)
X_projected_train = pca.fit_transform(X_std_train)
X_projected_test = pca.transform(X_std_test)

12. Visualize your principal components

In [62]:
pd.DataFrame(X_projected_train).head()

0         1         2
0  4.328850 -0.580995 -0.614033
1 -3.230328 -0.387308 -1.064588
2 -2.374479 -1.772095  0.326791
3  3.683354 -2.856250  0.456674
4  2.951256 -1.151197 -1.289172

13. Check the explained variance ratio from your principal components

In [63]:
pca.explained_variance_ratio_

array([0.19200008, 0.0982849 , 0.0632323 ])

In [64]:
pca.explained_variance_ratio_.sum()


0.35351727294712165

Les 3 premières colonnes ne portent que 35% de l'information

14. Fit your `RandomForestRegressor` on your train set where you applied PCA, check out your score on your test set. 

In [65]:
my_random_forest.fit(X_projected_train, y_train)
my_random_forest.score(X_projected_test, y_test)

0.7892136338968512

15. Use `cross_val_score` again to see your model's overall performance. What can you say about it?

In [66]:
scores = cross_val_score(my_random_forest, X_projected_train, y_train, cv=25)
scores.mean()

0.8303323403457773

On avait 83% et 94% là où on a 79% et 83%

16. Finally, use `scatter_3d` from `plotly.express` and `go.Scatter3d` from `plotly.graph_objects` to visualize a 3D graphs with all Principal Components from train and from test.

In [68]:

fig = px.scatter_3d(X_projected_train, x=0, y=1, z=2)

fig.add_trace(
  go.Scatter3d(x=X_projected_test[:, 0], y=X_projected_test[:, 1], z=X_projected_test[:, 2])
)

# Render on notebook
fig.show()

In [1]:
df_plot = pd.DataFrame(X_projected_train)
df_plot.columns = ['PC1', 'PC2', 'PC3']
df_plot['SalePrice'] = list(y_train)

fig = px.scatter_3d(df_plot, x='PC1', y='PC2', z='PC3', color='SalePrice')
fig.show()

NameError: name 'pd' is not defined