In [1]:
import numpy as np

In [3]:
A = np.array([
  [-1.41, -1.60],
  [-0.71, -0.30],
  [ 0.00, -0.09],
  [ 0.71, 0.56],
  [ 1.41, 1.42],
])

In [13]:
U, S, Vh = np.linalg.svd(A, full_matrices=True)

In [14]:
Vh

array([[ 0.70697243,  0.70724111],
       [ 0.70724111, -0.70697243]])

In [15]:
S

array([3.13927545, 0.34270928])

In [16]:
U


array([[-0.67799622,  0.39084417, -0.0764168 ,  0.16778131,  0.59461909],
       [-0.22748012, -0.84634259,  0.17186929,  0.39988533,  0.20617876],
       [-0.02027592,  0.18566033,  0.98170638, -0.0359656 , -0.00884271],
       [ 0.286055  ,  0.30999052, -0.02107067,  0.89658754, -0.13328626],
       [ 0.63744438, -0.0195235 ,  0.02073737, -0.08233115,  0.76555538]])

In [17]:
Bob = Vh.dot(S).dot(U)

ValueError: shapes (2,) and (5,5) not aligned: 2 (dim 0) != 5 (dim 0)