In [17]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

import numpy as np
import pandas as pd

# import plotly.express as px


import random
from numpy.random import uniform
import math
from numpy import linalg as la


In [18]:
X, _ = load_iris(return_X_y=True, as_frame=True)
X.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [19]:
sc = StandardScaler()
X = sc.fit_transform(X)
print (X.shape)
X[:5]

(150, 4)


array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [20]:
kmeans = KMeans(n_clusters=3, random_state=0, n_init="auto")
kmeans.fit(X)


c:\Users\phili\anaconda3\envs\jedha\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3, n_init='auto', random_state=0)

In [21]:
kmeans.cluster_centers_

array([[-1.01457897,  0.85326268, -1.30498732, -1.25489349],
       [-0.01139555, -0.87600831,  0.37707573,  0.31115341],
       [ 1.16743407,  0.14530299,  1.00302557,  1.0300019 ]])

In [26]:
class My_KMeans():
  """kMeans simple implemantation"""

  def __init__(self, n_clusters=2, random_state='None', n_init="auto", n_iter="100"):
    self.n_clusters_    = n_clusters
    self.random_state_  = random_state
    self.n_init_        = n_init 
    self.n_iter_        = n_iter

    random.seed(self.random_state_)
    
  

  # X est un ensemble de 'nb lignes' points qui ont chacun 'nb colonnes' dimensions 

  # Algo : 
  # Trouver les min et max sur chaque dimension
  # Placer k centroides dans le "cadre" à n dim MAIS pas trop rapprochés
  # Utiliser random_state pour la répétabilité
  # Calculer la distance entre 1 centroide et tous les points
  # Associer chaque point au centroide le plus proche
  # Deplacer chaque centroide en le mettant au milieu des points qui lui sont tattachés
  # Boucle jusqu'à nb_iter atteint ou move<epsilon
  def fit(self, X):
    
    _, nb_dim = X.shape
    self.centroids_ = np.empty((self.n_clusters_, nb_dim))

    # Trouver les min et max sur chaque dimension (colonne)
    # min contient les min des colonnes (idem pour max)
    min = np.min(X, axis=0)
    max = np.max(X, axis=0)

    # Placer k centroides dans le "cadre" à n dim MAIS pas trop rapprochés
    # Pour l'instant, on va pas tester si ils sont trop rapprochés
    # self.centroids_ = [uniform(min, max) for i in range(self.n_clusters_)]

    # Pour chaque centroide
    for k in range(self.n_clusters_):
      # Pour chaque dimension, on génère un nb entre le min et le max de la dim en question
      # version vectorisée de bob = random(min, max)
      self.centroids_[k] = uniform(min, max)

    for k in range(self.n_clusters_):
      print(self.centroids_)
    
    return self





In [23]:
X = np.array([  [-100,  -50,  -10],
                [  50,   70,  100],
                [ 200,  250,  300],
                [ 500,  750,  999],
              ])

X[2]

array([200, 250, 300])

In [29]:
kmeans2 = My_KMeans(n_clusters=2, random_state=0, n_init="auto")
kmeans2.fit(X)

[[348.50809123 173.31853734 353.2828471 ]
 [487.87706708 717.25790805  71.0040368 ]]
[[348.50809123 173.31853734 353.2828471 ]
 [487.87706708 717.25790805  71.0040368 ]]
