# Numpy Matrix Multiplication

3 ways to perform NumPy matrix multiplication

1. `np.dot(array a, array b)`      : returns the scalar product or dot product of two arrays
1. `np.matmul(array a, array b)`   : returns the matrix product of two arrays
1. `np.multiply(array a, array b)` : returns the element-wise matrix multiplication of two arrays


https://www.educative.io/blog/numpy-matrix-multiplication

In [11]:
import numpy as np
import pprint 


## Scalar Product

### With a number

In [29]:
A = 2

B = [
  [6, 7],
  [8, 9]
]
print(type(B))
 
C = np.dot(A, B)
pprint.pp(C)

<class 'list'>
array([[12, 14],
       [16, 18]])


In [33]:
A = 2

B = np.array([
  [6, 7],
  [8, 9]
])
print(type(B))

 
C = np.dot(A,B)
pprint.pp(C)
print()

C = A*B
pprint.pp(C)


<class 'numpy.ndarray'>
array([[12, 14],
       [16, 18]])
array([[12, 14],
       [16, 18]])


### Vector

In [53]:
A = [1, 2, 3]

B = [
  [0, 1],
  [1, 2],
  [3, 1],
]
 
# A comme vecteur ligne 
C = np.dot(A,B)
pprint.pp(C)

array([11,  8])


In [50]:
A = np.array([1, 2, 3])
B = np.array([
  [0, 1],
  [1, 2],
  [3, 1],
])
 
C = A.dot(B)
pprint.pp(C)


array([11,  8])


In [39]:
A = np.array([2, 4])
B = np.array([6, 7])
 
C = A.dot(B)
pprint.pp(C)

# C = np.cross(A, B)
# pprint.pp(C)

40


In [55]:
A = np.array([2, 1])

B = [
  [1, 2],
  [3, 1]
]
 
# A comme vecteur ligne 
C = A@B
pprint.pp(C)

array([5, 5])


In [15]:
A = np.array([2, 4])

B = np.array([
  [6, 7],
  [8, 9]
])
 
# A comme vecteur ligne 
C = A@B
pprint.pp(C)

array([44, 50])


In [16]:
B = [
  [6, 7],
  [8, 9]
]

A = [2, 4]

# A comme vecteur colonne 
C = np.dot(B, A)
pprint.pp(C)

array([40, 52])


In [23]:
A = [2, 4]

B = [1, 3]
 
 
C = np.dot(A,B)
pprint.pp(C)

14


In [27]:
A = np.array([2, 4])
print(A.shape)

B = np.array([1, 3])
print(B.shape)
 
 
C = np.dot(A,B)
pprint.pp(C)


(2,)
(2,)
14


### Matrices

In [17]:
A = [
  [1, 3, 5],
  [2, 4, 6],
]
      
B = [
  [1, 4],
  [2, 5],
  [3, 6],
]

C = np.dot(A,B)
pprint.pp(C)

array([[22, 49],
       [28, 64]])


## Matmul

2 2D arrays

Can’t use scalar values as input. 

If one argument is a 1-d array, the function converts it into a NumPy matrix by appending a 1 to its dimension. 
This is removed after the multiplication is done.

If one of our arguments is greater than 2-d, the function treats it as a stack of matrices in the last two indexes.

The matmul() method is great for times when we’re unsure of what the dimensions of our matrices will be.

In [18]:
A = [
  [1, 3, 5],
  [2, 4, 6],
]
      
B = [
  [1, 4],
  [2, 5],
  [3, 6],
]

C = np.matmul(A,B)
pprint.pp(C)

array([[22, 49],
       [28, 64]])


In [19]:
A = [
  [5, 0],
  [0, 5]
]
 
B = [5, 2]

C = np.matmul(A,B)
pprint.pp(C)
 

array([25, 10])


## Multiply

* Both matrices should have the same dimensions.
* Element-wise multiplication
* Hadamard Product
* Multiples every element of the first NumPy matrix by the equivalent element in the second matrix. 

In [20]:
A = np.array([
  [1, 3, 5, 7, 9], 
  [2, 4, 6, 8, 10]
])

B = np.array([
  [1, 2, 3, 4, 5], 
  [5, 4, 3, 2, 1]
])

C = np.multiply(A,B)
pprint.pp(C)

array([[ 1,  6, 15, 28, 45],
       [10, 16, 18, 16, 10]])
